경북대 FE 김규회 STEP 0 제출합니다.
kakao-tech-campus-2nd-step2/react-product-order pull request #1
Opened 2024-07-15 12:38 UTC by KimKyuHoi

# STEP 0에서는 현재 구현할 기능을 README에 작성하는 것을 알고 있습니다.

# 카카오 테크 캠퍼스 - 프론트엔드 카카오 선물하기 편

## 1단계 기능 구현할 내용

- 결과 링크를 참고하여 상세 페이지 및 상품 결제 페이지의 UI를 구현한다.
  - 이 과정에서 UI를 chakra-ui 사용해서 구현한다. (단, 직접 구현해도 무방하나 다른 UI 라이브러리 사용은 금지)
  - 이번 과제는 Form을 다루는 것이 중점이기 때문에 UI 구현에 어려움을 겪는다면 임의로 변경해도 됨
- 세 페이지에서 첨부된 oas.yaml 파일의 /api/v1/products/{productId}/detail, /api/v1/products/{productId}/options를 참고하여 API를 구현한다.
  없는 상품의 경우 메인 페이지로 연결되도록 한다.
- 나에게 선물하기 버튼 클릭 시 로그인이 되어있지 않다면 로그인 페이지로 이동한다.
- React Hook Form 등의 라이브러리를 사용하지 않으며 React의 form, ref, state만 사용하여 구현한다.

## 2단계 기능 구현할 내용

- 결제 페이지의 Form을 validation 해요. (4주차 미션 결과물 참고)
  - 카드 메시지를 입력하지 않으면 메시지를 입력하라고 안내해요.
  - 카드 메시지가 100글자가 넘어가면 100자 이내로 입력하라고 안내해요.
  - 현금 영수증 checkbox 클릭 시 현금영수증 번호가 입력되었는지 확인해요.
  - 현금 영수증 입력은 숫자만 입력하도록 안내해요.

이렇게 작성하였고 수욜까지 개발을 진행할 계획입니다.

2024-07-17 19:45 UTC, KimKyuHoi commented
새로운 PR을 날릴수가 없어 기존 PR 자체 내에서 진행을 하였습니다. STEP 1 ~ STEP2 내용 구현하였습니다~

2024-07-19 11:51 UTC, danmin20 commented on src/api/hooks/useGetGoodsDetail.ts
> +};
저라면, api/goods 폴더 하위에 type.ts, api.ts를 만들어 훅과 타입을 분리시켜줄 것 같아요! 컴포넌트에서도 동일한 타입이 사용될 수 있으니까요~

2024-07-19 12:14 UTC, danmin20 requested changes
수고하셨습니다~!

2024-07-19 12:14 UTC, danmin20 commented on src/api/hooks/useGetGoodsDetail.ts
> +};
저라면, api/goods 폴더 하위에 type.ts, api.ts를 만들어 훅과 타입을 분리시켜줄 것 같아요! 컴포넌트에서도 동일한 타입이 사용될 수 있으니까요~

2024-07-19 12:14 UTC, danmin20 commented on src/api/hooks/useGetGoodsDetail.ts
> +};
1. props는 보통 컴포넌트에 사용되는 표현이에요.
2. GoodsDetailRequestParams를 그대로 사용해도 될 것 같은데 따로 정의하신 이유가 있을까요?
3. params가 id하나라면 그냥 (id: string) 으로 바로 넣어줘도 될 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/api/hooks/useGetGoodsOption.ts
> +  });
이 파일도 동일하고, 저라면 api/goods 폴더 내의 api.ts와 type.ts에 몰아넣어줄 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/components/features/Goods/Header.tsx
> +type Props = GoodsDetailRequestParams;
여기서도 { productId : string } 정도로 명확히 표현하는 게 좋을 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/hooks/useOrderFormContext.ts
> +export const useOrderFormContext = useFormContext<FormData>;
이정도는 따로 빼지 않고 컴포넌트에서 useFormContext를 각각 호출해줄 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/hooks/useOrderFormContext.ts
> +import type { FormData } from '@/types';
OrderFormData 정도로 더 구체적으로 네이밍해주는 게 좋을 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/types/index.ts
> +export interface GoodsDetailData extends GoodsData {
interface와 type을 혼용해서 사용하신 이유가 있을까요?

2024-07-19 12:14 UTC, danmin20 commented on src/api/hooks/useGetGoodsDetail.ts
> +};
저라면 GoodsDetailData를 GoodsDetailDto 정도로 명시하고 goods/type.ts에 같이 작성할 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/components/features/Order/index.tsx
> +const validateOrderForm = (values: FormData): { errorMessage?: string; isValid: boolean } => {
컴포넌트 밖으로 빼신 이유가 있을까요?

2024-07-19 12:14 UTC, danmin20 commented on src/components/features/Order/Fields/CashReceiptFields.tsx
> +      <Input {...register('cashReceiptNumber')} placeholder="(-없이) 숫자만 입력해주세요." />
Controller와 register는 어떤 기준으로 다르게 사용해주신 걸까요?

2024-07-19 12:14 UTC, danmin20 commented on src/components/features/Order/Fields/MessageCardsFields.tsx
> +  const { register } = useOrderFormContext();
여기서도 타입을 명시해주면 더 명확할 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/components/features/Order/index.tsx
> +    }
required:true 옵션을 사용해보는 것도 좋을 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/components/features/Theme/ThemeGoodsSection/index.tsx
>            {flattenGoodsList.map(({ id, imageURL, name, price, brandInfo }) => (
`flatMap()`을 사용해도 될 것 같아요~

2024-07-19 12:14 UTC, danmin20 commented on src/types/index.ts
> +};
저라면 api와 관련된 타입은 api/goods 하위에, 폼 타입은 폼을 사용하는 페이지 하위에 둘 것 같기도 하네요~

2024-07-19 12:14 UTC, merged