강원대 FE_윤채연 4주차 과제
kakao-tech-campus-2nd-step2/react-product-order pull request #105
Opened 2024-07-20 12:22 UTC by ychy61

안녕하세요 멘토님
항상 시간을 내어 피드백 해주셔서 감사합니다!

2024-07-20 12:51 UTC, yujo11 requested changes
안녕하세요 채연님~

간단한 코멘트들 남겼는데 확인해보시면 좋을거 같네요 ㅎㅎ 고생하셨습니다~~

2024-07-20 12:51 UTC, yujo11 commented on src/api/hooks/useGetProductDetail.ts
> +  const response = await fetchInstance.get(getProductDetailPath(params));
아래처럼만 사용해도 충분할거 같은데 함수를 별도로 정의하신 이유가 있나요?

```suggestion
  const response = await fetchInstance.get(`/v1/products/${params.productId}/detail`);
```

2024-07-20 12:51 UTC, yujo11 commented on src/api/hooks/useGetProductDetail.ts
> +export const useGetProductDetail = (productId: number): UseQueryResult<ProductDetailData> => {
useQuery의 옵션들도 같이 받을 수 있게 해주시면 hook을 더 유연하게 사용가능할거 같네요

2024-07-20 12:51 UTC, yujo11 commented on README.md
> +- 질문 1. 제어 컴포넌트와 비제어 컴포넌트의 차이가 무엇이고 제어 컴포넌트로 Form을 만들어야 하는 경우가 있다면 어떤 경우인지 예시와 함께 설명해주세요.
제어 컴포넌트와 비제어 컴포넌트를 사용했을 때 각각 어떤 이점이 있을까요?

2024-07-20 13:05 UTC, ychy61 commented on src/api/hooks/useGetProductDetail.ts
> +  const response = await fetchInstance.get(getProductDetailPath(params));
템플릿 코드에서 path 함수를 별도로 정의하는 방식을 보고, 저도 이와 같은 방식을 적용해 보았습니다.

2024-07-20 13:05 UTC, ychy61 commented on src/api/hooks/useGetProductDetail.ts
> +export const useGetProductDetail = (productId: number): UseQueryResult<ProductDetailData> => {
넵! 피드백 감사합니다. 수정해보도록 하겠습니다!

2024-07-20 13:06 UTC, ychy61 commented on README.md
> +- 질문 1. 제어 컴포넌트와 비제어 컴포넌트의 차이가 무엇이고 제어 컴포넌트로 Form을 만들어야 하는 경우가 있다면 어떤 경우인지 예시와 함께 설명해주세요.
제어 컴포넌트는 React의 상태를 통해 폼의 입력값을 관리하여 데이터 흐름을 일관적으로 유지하고 실시간으로 입력값을 검증할 수 있다는 이점이 있는 반면, 비제어 컴포넌트는 DOM 자체에 데이터를 저장하여 폼을 더 간단하게 구현할 수 있으며, 폼 데이터를 일괄적으로 처리하는데 이점이 있습니다.

2024-07-20 13:14 UTC, ychy61 commented
멘토님 피드백 감사합니다! 템플릿 코드에서 path 함수를 별도로 정의하는 방식을 보고, 저도 이와 같은 방식을 적용해 보았는데 혹시 수정하는게 좋을까요?

2024-07-20 13:15 UTC, ychy61 reviewed
멘토님 피드백 감사합니다! useQuery의 옵션들도 같이 받을 수 있도록 수정했습니다.
추가로 템플릿 코드에서 path 함수를 별도로 정의하는 방식을 보고, 저도 이와 같은 방식을 적용해 보았는데 혹시 수정하는게 좋을까요?

2024-07-21 12:48 UTC, yujo11 commented
>추가로 템플릿 코드에서 path 함수를 별도로 정의하는 방식을 보고, 저도 이와 같은 방식을 적용해 보았는데 혹시 수정하는게 좋을까요?

코드의 작성 이유가 궁금해서 남긴 부분이었습니다 ㅎㅎ 굳이 수정하지 않으셔도 될거 같아요

2024-07-21 12:49 UTC, yujo11 approved these changes
고생하셨습니다 채연님~~

2024-07-21 12:49 UTC, yujo11 commented on README.md
> +- 질문 1. 제어 컴포넌트와 비제어 컴포넌트의 차이가 무엇이고 제어 컴포넌트로 Form을 만들어야 하는 경우가 있다면 어떤 경우인지 예시와 함께 설명해주세요.
컴포넌트 리렌더링 측면에서도 어떤 차이가 있는지 찾아보시면 좋을거 같습니다!

2024-07-21 12:49 UTC, merged