Step1
kakao-tech-campus-2nd-step2/react-product-order pull request #15
Opened 2024-07-16 13:36 UTC by dlwltn0430

안녕하세요 멘토님! 4주차 과제 1단계 제출합니다.

2024-07-17 01:39 UTC, MiaJLee requested changes
고생하셨습니다 지수님~
이번주도 파이팅!

2024-07-17 01:39 UTC, MiaJLee commented on src/pages/Product/index.tsx
> +  const [quantity, setQuantity] = useState(1);
Controlled 컴포넌트를 선택하신 이유가 있을까요?
Uncontrolled 컴포넌트와 비교했을 때 어떤 차이점이 있을지, uncontrolled 를 사용했다면 어떻게 코드를 작성했을 것 같은지 답변 부탁해요!

2024-07-17 03:24 UTC, dlwltn0430 commented on src/pages/Product/index.tsx
> +  const [quantity, setQuantity] = useState(1);
사용자 입력이 발생할 때마다 즉시 상태가 업데이트되고, 사용자가 입력한 값을 실시간으로 검증할 수 있어 Controlled 컴포넌트를 선택했습니다! 
Controlled 컴포넌트를 사용하면 폼 요소의 값이 항상 리액트 상태와 동기화되어 있어, 값이 변경될 때마다 즉각적으로 상태를 업데이트할 수 있습니다. 반면 Uncontrolled 컴포넌트는 리액트가 아닌 돔 자체에서 폼 데이터의 값을 관리합니다. 초기 값을 설정할 수 있지만, 그 이후의 값 변경은 돔을 통해 직접 접근해야 합니다. 
Uncontrolled를 사용한다면 `const quantityRef = useRef<HTMLInputElement>(null);` 이런 식으로 dom 요소에 직접 접근하여 구현할 것 같습니다!

2024-07-17 03:24 UTC, dlwltn0430 commented
> 고생하셨습니다 지수님~ 이번주도 파이팅!

이번주도 잘 부탁드립니다😎

2024-07-18 09:08 UTC, MiaJLee approved these changes

2024-07-18 09:08 UTC, merged