부산대 FE_이세형 4주차 과제 Step2
kakao-tech-campus-2nd-step2/react-product-order pull request #16
Opened 2024-07-16 13:49 UTC by cla6shade

안녕하세요 멘토님-!

코드가 길고 알아먹기가 힘들어져서 Context를 사용해볼까 고민도 해봤지만 Context를 이용하여 입력 값 관리 시 값을 입력할 때마다 하위의 컴포넌트가 전부 리렌더링된다는 단점을 고려해서 기존의 controlled 방식을 계속 유지한 채 validation logic을 추가해봤습니다.

특히 구글폼에서 required 항목을 관리할 때 alert보다는 인풋 아래에 에러 메시지를 띄운다는 점을 참고해서 구현해봤는데, state로 관리하다보니 영.. 보기 좋지는 않았던것 같습니다.

이번 step도 잘 부탁드립니다.
항상 시간내어주셔서 정말 감사합니다!

2024-07-18 12:37 UTC, MiaJLee commented on src/components/organisms/product/ProductOrderForm.tsx
> +    }
validation 로직은 따로 함수로 분리해도 좋겠습니다-!

2024-07-18 12:46 UTC, MiaJLee commented on src/components/organisms/product/ProductMessageForm.tsx
> +          <Text color={textColors.error}>{messageFormError}</Text>
messageFormError가 빈 값일때는 해당 컴포넌트를 그릴 필요가 없는데 요렇게 짜신 이유가 있을까요?

2024-07-18 12:52 UTC, MiaJLee requested changes
세형님 고생 많으셨습니다-!
리뷰 확인해주세요!

2024-07-18 12:52 UTC, MiaJLee commented on src/pages/ProductOrderPage.tsx
> +            />
ProductMessageForm, ProductOrderForm에 동일한 messageFormError, setMessageFormError를 넘기고 있는 이유가 있나요?

2024-07-18 12:52 UTC, MiaJLee commented on src/components/organisms/product/ProductOrderForm.tsx
>      // console.log(body);
디버깅 코드는 제거해주세요!

2024-07-18 12:52 UTC, MiaJLee commented on src/pages/ProductOrderPage.tsx
> +            />
submit에 위의 두가지 폼의 에러를 체크해야 한다면, 제출하는 기능을 ProductOrderPage에 두는 것이 하이라키가 맞지 않을까? 하는 생각이 드는 것 같아요~ 한번 고민해보시면 좋겠습니다! 한쪽 폼의 에러를 sibling 컴포넌트가 확인하고 제출까지 담당하니 조금 헷갈리네요!

2024-07-18 13:31 UTC, cla6shade commented on src/pages/ProductOrderPage.tsx
> +            />
페이지에 validation logic을 함께 넣고 관리하려니 복잡해질것 같아서 form에 각각의 validation을 넣었는데.. 오히려 지금 보니 더 복잡한 것 같네요.
위쪽으로 빼서 수정해보겠습니다~!

2024-07-18 17:09 UTC, cla6shade commented
멘토님 안녕하세요,

지난번 Step2를 작성할 당시에 코딩하는 법을 잠시 까먹었나 봅니다.
지금 제가 보니 충격의 도가니탕이군요..

Step2를 거의 다시 짜다시피 해봤는데, 궁금한 점이 생겨 질문드립니다.

1. controlled 컴포넌트에서, 어떤 값을 입력했을 때 validation을 수행하도록 하기 위해 useEffect를 사용했는데요, useEffect를 사용하니 초기 렌더링 시 전달되는 공백 문자열에 대해서도 `잘못된 데이터다!`라고 validation이 수행됨을 알 수 있었는데요, 

초기 렌더링된 직후의 input 값에 대해서는 validation을 수행하지 않도록 하려면 어떻게 해야하는지 가장 이상적인 방법이 궁금합니다.

저의 경우에는 크게 두 가지 방식을 떠올렸습니다.

1.  `change event가 한 번 이상 트리거됐음`을 나타내는 state를 하나 두고, changeEvent 호출 시 해당 state를 변화시키고, `change event`가 한 번 이상 트리거됐을 때만 validation을 수행하도록 useEffect 내부에 로직 구현

2. useRef를 이용하여, 초기 렌더링 시점을 파악하고 초기 렌더링 시점이 아닐 때에만 validation 수행

두 방식 모두 시도해봤지만 1번 방식은 state를 예측하기가 매우 어려워져서(제 낮은 수준에서 어려웠습니다...) 중간에 revert로 되돌리고, 2번째 방식으로 구현해봤습니다. 하지만 2번째 방식 또한 리액트스럽지 않아서 불만족스러웠습니다.

부족한 코드이지만 리뷰 부탁드립니다. 감사합니다!

2024-07-18 17:11 UTC, cla6shade commented on src/components/organisms/product/ProductOrderForm.tsx
>      // console.log(body);
자꾸만 까먹네요 ㅠㅠ 다음 커밋부터 주의하겠습니다!

2024-07-18 17:13 UTC, cla6shade commented on src/components/organisms/product/ProductMessageForm.tsx
> +          <Text color={textColors.error}>{messageFormError}</Text>
제가 진짜 코딩하는 방법을 까먹었던것 같습니다..
별도의 boolean property로 렌더 여부를 제어하도록 변경했습니다!

2024-07-19 08:43 UTC, MiaJLee requested changes
리뷰 확인 부탁드려요!

2024-07-19 08:43 UTC, MiaJLee commented on src/hooks/useOrderFormValidation.ts
복잡한 validation을 따로 분리하신 것 잘 하셨습니다!
form에서는 view와 관련된 것들만 노출되니 훨씬 이해하기 좋은 코드가 되었네요.

2024-07-19 08:43 UTC, MiaJLee commented on src/hooks/useOrderFormValidation.ts
> +    receiptErrorCaption: FormErrorMessages.RECEIPT_NUMBER_NOT_NUMERIC,
hasXError, xErrorCaption의 거의 유사한 로직으로 동시에 수정되는 두가지 state들을 두고 있는데요.
state가 늘어난 만큼 side effect 가능성이 높아질 수도 있을 것 같아요.
hasError === true 인데 caption이 없다던지, 그 반대의 케이스도 있을 수 있죠.
단일 타입으로 바꾸어 caption의 타입에 `FormErrorMessages.NONE` 와 같은 타입을 추가하는건 어떨까요?
관리할 state가 줄어들어 더 나은 방법이 될 수 있을 것 같아요. 변수명도 더 포괄적으로
`cardMessageError: FormError.CARD_EMPTY` 와 같이 수정될 수 도 있겠네요.
한번 고민해보셔도 좋겠습니다~

2024-07-19 08:43 UTC, MiaJLee commented on src/hooks/useOrderFormValidation.ts
> +    receiptErrorCaption: FormErrorMessages.RECEIPT_NUMBER_NOT_NUMERIC,
댓글에 질문으로 남겨주신 input이 초기 상태일때 에러가 노출되는 이슈가 있었는데요~
modify 여부는 validation이 아닌 input value state와 관심사를 묶는 것도 방법이겠네요.
해당 input이 건드려진 적이 있는지에 대한 값이 어느 쪽과 더 가까운지 고민해보면 좋을 것 같아요.

validation은 동작하되, dirty 케이스에만 노출되게끔 처리할 수 있겠지요.
해당 state가 dirty한지 여부를 함께 관리할 수도 있을 것 같아요.
아래는 하나의 예시일 뿐이니 한번 고민해봐주세요!

ex)
```ts
const [message, setMessage] = useState({value: '', dirty: false}))
```

2024-07-19 11:05 UTC, MiaJLee approved these changes
세형님~
위 말씀드린 사항은 다음 pR에서 고려해주세요-! step2는 머지하겠습니다!

2024-07-19 11:05 UTC, merged