부산대 FE_차기은 4주차 과제 STEP1
kakao-tech-campus-2nd-step2/react-product-order pull request #18
Opened 2024-07-16 17:48 UTC by harugi7

안녕하세요 미아 멘토님!
이번 step1은 chakra-ui를 이용해서 페이지를 구성하고 '나에게 선물하기 버튼 클릭 시 로그인이 되어있지 않다면 로그인 페이지로 이동한다.'를 구현하는데 집중하였습니다...!
다소 코드가 지저분해서 가독성이 떨어질 것 같아 미리 죄송하다는 말씀 드리고 싶습니다...
step을 진행하면서 컴포넌트 사용하는 등 코드 리팩토링도 진행해보겠습니다! 
양해 부탁드립니다. 이번주도 화이팅입니다!!

2024-07-17 01:44 UTC, MiaJLee requested changes
고생하셨습니다 기은님~
리뷰 확인해주세요!

2024-07-17 01:44 UTC, MiaJLee commented on src/pages/Product/index.tsx
> +  const [quantity, setQuantity] = useState(1);
Controlled 컴포넌트를 사용하고 계시네요~
해당 방식을 사용하신 이유가 있을까요? Uncontrolled 컴포넌트와는 어떤 차이가 있는지 답변 부탁해요!

2024-07-17 01:44 UTC, MiaJLee commented on src/routes/path.ts
>  export const getDynamicPath = {
Static, dynamic path 를 이렇게 정리해두니 보기 편하고 좋네요~!

2024-07-17 06:04 UTC, harugi7 commented on src/pages/Product/index.tsx
> +  const [quantity, setQuantity] = useState(1);
사용자가 입력한 값이 즉시 UI에 반영되어 실시간 피드백을 줄 수 있고, 상태를 직접 관리하여 검증 로직이나 조건에 따른 값 변경을 쉽게 구현할 수 있기 때문에 사용하였습니다! 
Uncontrolled 컴포넌트는 React 컴포넌트의 상태를 업데이트하지 않고, DOM의 직접적인 참조를 통해 값을 가져오거나 업데이트합니다.

2024-07-18 09:08 UTC, MiaJLee approved these changes

2024-07-18 09:08 UTC, merged