전남대 FE_정서윤 4주차 과제
kakao-tech-campus-2nd-step2/react-product-order pull request #20
Opened 2024-07-17 05:44 UTC by yunn23

### 아직 과제 진행중입니다
오류 해결을 위해 과제 완성 전 pr 생성하였습니다.

2024-07-17 15:28 UTC, taehwanno requested changes
아직 구현 중이신거 같아서, 리뷰 가능한 상태가 될 때 우측 상단에 review re-request 누르셔서 요청 부탁드려요.

2024-07-17 15:28 UTC, taehwanno commented on src/components/features/Layout/ProductDetail.tsx
> +  console.log('ProductDetail: ', productDetail)
console.log는 커밋에는 포함되지 않도록 하는게 권장됩니다.

2024-07-18 06:14 UTC, yunn23 commented
step1 구현 완료

2024-07-18 06:26 UTC, yunn23 commented on src/components/features/Layout/ProductDetail.tsx
> +  console.log('ProductDetail: ', productDetail)
커밋 찍으면서 통신 부분 구현하고 있어서 마지막으로 제출할때는 console.log 모두 삭제하겠습니다!

2024-07-19 14:19 UTC, taehwanno requested changes
고생하셨습니다. 몇 가지 피드백 드려요!

2024-07-19 14:19 UTC, taehwanno commented on src/pages/Order/index.tsx
> +
```
export interface OrderLocationState {
  productDetail: ProductDetail;
  quantity: number;
  price: number;
}
```

location.state는 기본적으로 타입이 any라서 타입 안전하게 소비하기 위해 26번 라인 위에 location state 타입을 선언해두고 타입을 명시해주는게 좋겠습니다.

```suggestion
  const { productDetail, quantity, price } = (location.state || {}) as OrderLocationState;
```

2024-07-19 14:19 UTC, taehwanno commented on src/components/features/Layout/ProductDetail.tsx
> +      navigate(RouterPath.order, { state: { productDetail: detail, quantity, price } });
```suggestion
      const state: OrderLocationState = { productDetail: detail, quantity, price };
      navigate(RouterPath.order, { state });
```

location.state를 사용할 때는 state를 전달하는 곳과 소비하는 곳이 달라서 state의 변화가 있을 때 타입 안전하게 처리하기 위해서는 소비하는 곳에서 state의 타입을 선언하고 이를 전달하는 곳에서 선언한 타입에 의존하는게 좋습니다. 그럼 key가 다르게 전달되거나 타입이 다르다면 에러가 발생할테니까요.

추가로 생각해볼만한 지점으로는 `/order` URL에 직접 접근했을 때 어떻게 대응할지 문제가 있습니다. 이때는 location.state가 없을테니까요. location.state를 통해 전달하는 데이터 구조가 복잡하지 않다면 URL을 하나의 리소스로 바라보고 URL query string으로 전달하는 방법도 있습니다. 이렇게 하면 페이지에서 의존하고 있는 데이터가 URL에 존재하니까 유저가 URL을 통해 특정 페이지부터 다시 시작할 수 있다는 장점도 있구요. 선택의 문제이긴 합니다.

2024-07-19 14:19 UTC, taehwanno commented on src/pages/Order/index.tsx
> +  });
1. controlled, uncontrolled 두 가지 형태를 모두 혼용해서 form을 구현하셨네요. 이렇게 하신 이유는 어떤걸까요?
2. 일관된 패턴을 적용하기 위해 하나의 형태만 적용하는게 좋아보이는데 개선해본다면 controlled 또는 uncontrolled 중에 어떤 방향으로 선택하시겠으며 그 이유는 무엇일까요?

2024-07-20 11:36 UTC, yunn23 commented on src/components/features/Layout/ProductDetail.tsx
> +      navigate(RouterPath.order, { state: { productDetail: detail, quantity, price } });
오 /order URL 직접 접근 관련해서도 한 번 생각해보겠습니다 감사합니다.

2024-07-20 12:10 UTC, yunn23 commented on src/pages/Order/index.tsx
> +  });
1. 아직 개념 확립이 제대로 되지 않은 상태에서 과제를 구현하다보니 발생한 문제 같습니다. 의도하지는 않았습니다.. 다시 관련 자료를 읽어보면서 공부하여 controlled 형태로 통일되도록 수정하였습니다.
2. 일관된 패턴을 적용하기 위해 form을 controlled 컴포넌트로 통일하였습니다. controlled는 useState를 사용하며, 값이 변경됨을 실시간으로 감지할 수 있으므로, 폼에 잘못된 데이터가 입력되고 있으면 바로 잡기 용이하기 때문에 controlled 컴포넌트로 통일하였습니다. uncontrolled는 useRef를 사용하며, 전통적인 HTML처럼 DOM에 제어되는 input 방식입니다. 따라서 입력 값을 추적하고 검증하기 어렵기 때문에 controlled 컴포넌트가 더 적합할 것이라 판단하였습니다.

2024-07-20 12:10 UTC, yunn23 commented
step1, 2 피드백 반영하여 코드 수정하였습니다.

2024-07-21 01:26 UTC, taehwanno approved these changes
고생하셨습니다.

2024-07-21 01:51 UTC, merged