강원대 FE_정다연 4주차 STEP1
kakao-tech-campus-2nd-step2/react-product-order pull request #29
Opened 2024-07-17 15:43 UTC by dandamdandam

안녕하세요 멘토님!

이번 과제에서는 상품 상세페이지를 보여주고, 나에게 선물하기를 클릭할 시 주문하기 페이지로 넘어가는 기능을 구현했습니다.

- 주문 수량은 상품 상세페이지에서 세팅하는 데, 이 데이터를 주문하기 페이지에서 사용하기 위해 sessionStorage를 이용하였습니다. 추가로 storage 재사용성을 높이기 위해 관련해서 리팩토링을 진행하였습니다(강사님이 주신 코드를 그대로 이용했습니다..!) [feat: implement saving orderHistory](https://github.com/kakao-tech-campus-2nd-step2/react-product-order/commit/e3ff5a2ebdf59c0d3b901d4a97d36a9fe62da52f)
- chakra UI는 간략 임포트 방식으로 불러왔습니다. 관련해서 임포트 하지 않으면(extendBaseTheme로 지정하지 않으면) UI 스타일이 적용되지 않는 것을 확인했습니다.
  - chakraTheme.components로 부터 구조분할해서 불러오면서 extendBaseTheme에다 지정하여 중복되는 코드를 없애고 싶었으나 아직 방법을 찾지 못했습니다.
- formdata는 변화를 추적할 필요가 없다고 생각해 FormData 객체로 받아오는 형식으로 구현하였습니다.
- cors 에러발생 [feat: handle order submit](https://github.com/kakao-tech-campus-2nd-step2/react-product-order/commit/a96380ca9573ee70142b3f3b4c436f7552918b07)
  ![image](https://github.com/user-attachments/assets/73b8f455-8475-4d6c-bbc0-d39d4f4d9f7c)
  ![image](https://github.com/user-attachments/assets/c49ceaa8-71e6-4e93-9d2d-c8a56db81a3b)
  - postman으로도 되지 않는 것을 보면, 서버 쪽에서 오리진 설정이 되지 않아서 인 것 같다
  - 이렇게 생각했는데, 맞는 판단인 걸까요?

2024-07-19 10:01 UTC, lazy-sky requested changes
안녕하세요, 다연님

포스트맨 에러 부분을 보시면 `405 Method Not Allowed`라고 써진 걸 확인할 수 있습니다. 따라서 메소드부터 확인하셔야 할 거 같네요.

한편 전체적으로 페칭된 데이터에 assertion이나 옵셔널 체이닝이 많이 사용되어 데이터를 올바르게 전달하지 못하는 경우들이 왕왕 있는 것 같습니다. 각종 페이지를 테스트해보시고 개발자 도구 콘솔창에서 어떤 에러 메시지 혹은 경고가 뜨고 있는지 확인해보시면 좋을 것 같습니다.

2024-07-19 10:01 UTC, lazy-sky commented on src/App.tsx
>  axios.defaults.baseURL = 'https://react-gift-mock-api-self.vercel.app/api/v1';
baseUrl, queryClient를 관리하기에 최상단 App보다 더 나은 위치가 있을 거 같습니다.

2024-07-19 10:01 UTC, lazy-sky commented on src/pages/Order/index.tsx
> +    const productDetail = useData<ProductDetailData>(`/products/${orderHistory?.productId}/detail`);
orderHistory가 제대로 fetch되지 않은 상태라면 이 호출에서 어떤 문제가 발생할 수 있지 않을까요?

2024-07-19 10:01 UTC, lazy-sky commented on src/pages/Order/index.tsx
> +                            imageURL={productDetail!.data!.detail.imageURL}
assertion(!)은 가급적 사용하지 않는 것이 좋습니다. 써야만 하는 상황이 되었다는 건 데이터 페칭 로직이 뭔가 잘못되었을 확률이 높아요.

2024-07-20 04:22 UTC, merged

2024-07-22 02:51 UTC, dandamdandam commented on src/pages/Order/index.tsx
> +                            imageURL={productDetail!.data!.detail.imageURL}
위 코드는 
  **isLoading이 false**이고(true일 경우 return <LoadingUI/> 이 대신 실행됨),
  **httpStatusCode가 200**이(그 외 코드를 가지는 경우 navigate에 의해 타 페이지로 라우팅 됨)
여야만 실행됩니다. 이러면 productDetail.data가 null이나 undefined가 아닐 것이라는 확신에서 assertion을 일단 사용했습니다.

assertion을 사용하지 않으려면,
1. null인 경우 default 값을 넣어줄 수 있습니다. -> 하지만 사실상 사용되지 않을 코드입니다.
2. isLoading가 false이고 httpStatusCode가 200인 경우 data가 비지 않는다는 사실을 명시해줍니다. -> 어떻게 명시해줄지를 모르겠습니다.. 조건부 타입으로 가능할까요?

2024-07-22 03:08 UTC, dandamdandam commented on src/pages/Order/index.tsx
> +    const productDetail = useData<ProductDetailData>(`/products/${orderHistory?.productId}/detail`);
/products//detail로 잘못된 요청을 보내게 될 것 같습니다. orderHistory가 비었는지 확인하는 연산을 추가했습니다!

https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/82/commits/c283c1cde8ec67621062fb13715effa59d76ef88

2024-07-22 03:26 UTC, dandamdandam commented on src/App.tsx
>  axios.defaults.baseURL = 'https://react-gift-mock-api-self.vercel.app/api/v1';
lib 폴더에 설정파일로 분리했습니다!

https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/82/commits/88517605d4a53483f5cf078ddd094ff95864b8a4

2024-07-22 05:09 UTC, lazy-sky commented on src/pages/Order/index.tsx
> +    const productDetail = useData<ProductDetailData>(`/products/${orderHistory?.productId}/detail`);
아마 `undefined`가 string화 되어 들어갈 거예요.

2024-07-22 05:12 UTC, lazy-sky commented on src/pages/Order/index.tsx
> +                            imageURL={productDetail!.data!.detail.imageURL}
이전에 한 번 언급했다시피 우리 클라이언트는 서버에서 오는 데이터를 확신해선 안됩니다. 나아가서 네트워크 등 다른 이슈가 있을 수도 있구요. 서버의 상태와 데이터가 어떠하든 클라이언트는 유저에게 적절한 화면을 보여줘야 합니다. 이를 위해선 여러 상황을 고려한 적절한 분기처리가 필요하겠죠. 
로딩 상태 처리, 에러에 따른 화면 처리, 기대하지 않았던 데이터에 대한 상태 처리 등... (우리는 리액트를 사용하고 있으니, Suspense, ErrorBoudary 등의 도구를 활용하는 것도 좋은 방법입니다)