충남대 FE_김지안_4주차 과제 STEP1, 2
kakao-tech-campus-2nd-step2/react-product-order pull request #37
Opened 2024-07-18 09:54 UTC by KimJi-An

안녕하세요 멘토님, 충남대학교 김지안 입니다.
4주차 과제 1, 2단계 제출합니다.
3단계는 기존에 만든 form과 input을 react-hook-form으로 변경하는 것이라 1, 2단계 리뷰가 완료된 후에 제출하도록 하겠습니다.

감사합니다!

2024-07-19 14:41 UTC, taehwanno requested changes
고생하셨습니다. 피드백 드려요!

2024-07-19 14:41 UTC, taehwanno commented on src/components/features/Product/ProductDetailSection/index.tsx
> +export const ProductDetailSection = (data: GoodsData) => {
```suggestion
interface ProductDetailSectionProps {
  name: string;
  imageURL: string;
  price: {
    sellingPrice: number;
  }
}

export const ProductDetailSection = (props: ProductDetailSectionProps) => {
```

GoodsData에는 여러 속성이 있지만 컴포넌트 내부에서는 3가지 속성만 소비하고 있네요. 더 넓은 타입으로 인해 소비하지 않은 데이터에 대한 의존성을 가지게 되는거라 컴포넌트에서 필요한 데이터 의존성만 따로 타입을 선언해서 사용하는게 좋겠습니다.

[결합도 (Coupling)](https://en.wikipedia.org/wiki/Coupling_(computer_programming))의 종류 중에 Stamp coupling (data-structured coupling)에 해당한다고 볼 수 있겠습니다.

2024-07-19 14:41 UTC, taehwanno commented on src/pages/Product/index.tsx
> +            brandInfo={data.brandInfo}
```suggestion
            name={data.name}
            imageURL={data.imageURL}
            price={data.price}
```

바로 위에 언급드린 피드백을 반영한다면 필요한 데이터 의존성만 전달받게 되므로 불필요한 props 전달은 제거할 수 있겠죠.

2024-07-19 14:41 UTC, taehwanno commented on src/components/features/Product/ProductOrderSection/index.tsx
> +export const ProductOrderSection = (ProductData: GoodsData) => {
ProductOrderSection도 ProductDetailSection에 드린 Stamp coupling의 문제가 있어서 같이 해결해보면 좋겠습니다.

2024-07-19 14:41 UTC, taehwanno commented on src/components/features/Order/PaymentInfoSection/index.tsx
> +  const cashReceiptNumberRef = useRef<HTMLInputElement>(null);
1. form 구현시 uncontrolled (`cashReceiptNumberRef`), controlled (`isCashReceipt`) 2가지를 모두 혼용해서 구현하고 있네요. 이렇게 2가지를 혼용한 이유는 어떤걸까요?
2. 하나의 방향만 적용해서 일관되게 작성한다면 어떤 방향을 선택하시겠어요? 그 이유도 궁금합니다.

2024-07-19 14:44 UTC, taehwanno requested changes
몇 가지 추가 피드백 드려요.

2024-07-19 14:44 UTC, taehwanno commented on src/pages/Order/index.tsx
> +  const quantity = location.state?.quantity ?? 1;
https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/20#discussion_r1684433892 코멘트와 동일한 피드백드려요. location.state를 타입 안전하게 소비할 수 있게 타입 정의가 되면 좋겠습니다.

2024-07-19 14:44 UTC, taehwanno commented on src/components/features/Product/ProductOrderSection/index.tsx
> +      navigate(getDynamicPath.order(ProductData.id), { state: { quantity } });
https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/20#discussion_r1684440551 코멘트와 동일한 맥락의 피드백 드려요.

2024-07-19 15:26 UTC, KimJi-An commented on src/components/features/Product/ProductDetailSection/index.tsx
> +export const ProductDetailSection = (data: GoodsData) => {
필요한 데이터의 타입만 interface로 작성해서 사용하는 방법이 있었군요. 감사합니다!

2024-07-19 15:54 UTC, KimJi-An commented on src/components/features/Order/PaymentInfoSection/index.tsx
> +  const cashReceiptNumberRef = useRef<HTMLInputElement>(null);
1. 처음에는 uncontrolled 방식 (`cashReceiptNumberRef`)을 사용해서 구현을 시작했는데, 이후에 현금 영수증 체크박스 클릭 여부를 이용하기 위해 controlled 방식 (`isCashReceipt`)을 사용해서 상태 관리를 추가하게 되었습니다. 두 가지 방식을 혼용하게 된 이유는 점진적으로 기능을 추가하면서 발생한 결과입니다.
2. 하나의 방식만 적용해서 일관되게 작성한다면 controlled 방식을 선택할 것 같습니다. 사용자의 입력 값들을 상태로 관리하면 값의 변경을 좀 더 명확하게 추적, 제어할 수 있을 것 같습니다. `isCashReceipt`를 추가하게 된 이유도 현금 영수증 신청 여부에 따라 번호 입력 필드의 유효성 검사를 다르게 처리하기에 좋겠다는 생각이 들었기 때문입니다.

2024-07-21 01:46 UTC, taehwanno approved these changes
고생하셨습니다.

2024-07-21 01:47 UTC, merged