부산대 FE_차기은 4주차 과제 Step2
kakao-tech-campus-2nd-step2/react-product-order pull request #41
Opened 2024-07-18 13:54 UTC by harugi7

step2 제출합니다! 더운 여름 화이팅입니다...😎

2024-07-18 22:10 UTC, MiaJLee requested changes
기은님 고생하셨습니다-! 리뷰 확인해주세요 !

2024-07-18 22:10 UTC, MiaJLee commented on src/pages/Product/index.tsx
> +                onChange={(e) => setQuantity(Math.min(Number(e.target.value), giftOrderLimit || 0))}
Math.min 을 사용하신 이유가 있나요??

2024-07-19 04:10 UTC, harugi7 commented on src/pages/Product/index.tsx
> +                onChange={(e) => setQuantity(Math.min(Number(e.target.value), giftOrderLimit || 0))}
입력된 값 (e.target.value)을 숫자로 변환한 후, giftOrderLimit과 비교하여 최소값을 quantity 상태 변수로 설정하기 위해서 Math.min을 사용하였습니다! 아님 삼항 연산자를 사용해도 될 것 같습니다!

2024-07-19 08:44 UTC, MiaJLee requested changes
기은님 리뷰 확인 부탁해요~

2024-07-19 08:44 UTC, MiaJLee commented on src/pages/Order/index.tsx
> +  const [isLoading, setIsLoading] = useState(true
여기 오타가 있어요~

2024-07-19 08:44 UTC, MiaJLee commented on src/pages/Order/index.tsx
> +  };
여기도 오타로 보여요~
맘이 급하시더라도 제출 전에는 꼭 개발 모드 실행해보시고, 에러나 워닝은 없는지 테스트 해주세요!

2024-07-19 08:44 UTC, MiaJLee commented on src/pages/Product/index.tsx
> +                onChange={(e) => setQuantity(Math.min(Number(e.target.value), giftOrderLimit || 0))}
앱이 제대로 실행이 되지 않아서 제가 테스트는 못해봤는데요~
해당 인풋에 직접 (버튼 클릭하지 않고) -1 과 같은 음수 값도 입력이 되는 것일까요??

로직을 이해하기에는 위의 방식보다는 삼항연산자나 따로 함수로 빼는게 자연스러울 것 같아요

2024-07-19 08:59 UTC, harugi7 commented
음수 값도 입력이 되어 이 부분 수정하겠습니다!
금요일까지 step별 제출이 어느정도 마무리되어야해서 step3, 4를 먼저 진행하여 제출하였습니다...!
혹시 step3, 4에 수정한 부분을 push해도 될까요?

2024-07-19 09:22 UTC, harugi7 commented
미아님 수정하였습니다! 확인 부탁드립니다!

2024-07-19 10:38 UTC, MiaJLee approved these changes

2024-07-19 10:38 UTC, merged