부산대 FE_차기은 4주차 과제 Step3, 4
kakao-tech-campus-2nd-step2/react-product-order pull request #61
Opened 2024-07-19 06:49 UTC by harugi7

미아 멘토님 4주차 과제 완료해서 pr 올립니다! 이번주도 너무너무 수고하셨습니다.

2024-07-19 11:11 UTC, MiaJLee requested changes
기은님- 이번주도 고생하셨습니다 :)
코멘트 확인해주세요!

2024-07-19 11:11 UTC, MiaJLee commented on src/pages/Order/index.tsx
> +    console.log(data);
디버깅 코드 제거해주세요!

2024-07-19 11:11 UTC, MiaJLee commented on src/pages/Order/index.tsx
> +
zod를 사용하셨네요~
zod의 역할은 무엇인가요?
사용하시면서 느낀 장단점이 있나요?

2024-07-19 11:13 UTC, harugi7 commented on src/pages/Order/index.tsx
> +    console.log(data);
헉 넵!!

2024-07-19 11:17 UTC, harugi7 commented on src/pages/Order/index.tsx
> +
zod는 좀 더 간편하고 쉽게 입력 값의 유효성 검사를 할 수 있게 합니다.
스키마에서 정의된 타입을 자동으로 추론하여 사용할 수 있다는 점이 편리했습니다!
zod의 API는 매우 직관적인 편이라 처음 사용하는 편임에도 이해하기 쉬웠지만 처음 사용해봐서 아직은 어색한 탓인지 코드가 복잡하게 짜여지기도 하였습니다...!

2024-07-20 11:31 UTC, MiaJLee approved these changes
고생하셨습니다-!

2024-07-20 11:31 UTC, merged