부산대 FE_이세형 4주차 과제 Step3
kakao-tech-campus-2nd-step2/react-product-order pull request #63
Opened 2024-07-19 06:59 UTC by cla6shade

안녕하세요 멘토님-!

날씨가 덥고 습해서 가만히 있기만 해도 축축 쳐지는 시기인듯 합니다..
그럼에도 시간내서 멘토링해주셔서 항상 감사드립니다!

아직 선택사항까지 구현하지는 못했는데, 과제 제출이 금일 자정까지라 부득이하게 먼저 PR을 올리게 되었습니다..
주말동안 조금 더 고도화한 후 푸쉬해보겠습니다!

2024-07-19 11:20 UTC, MiaJLee requested changes
날도 더운데 힘내서 작업해주셨네요! 고생하셨습니다 :)
현재 컨플릭트가 나고 있는데 리뷰와 함께 한번 확인 해주세요!

2024-07-19 11:20 UTC, MiaJLee commented on src/components/organisms/product/ProductOrderForm.tsx
> +              value: getValues().hasCashReceipt,
`getValues()`를 사용하신 이유가 있을까요?
'react-hook-form'의 Controller 컴포넌트를 활용한다면 어떻게 수정해볼 수 있을까요?

2024-07-19 11:20 UTC, MiaJLee commented on src/hooks/useOrderFormValidation.ts
> +  });
이 부분은 step2 PR에서 코멘트 드린 내용에 대해 어떻게 생각해보셨는지 궁금해요!

2024-07-19 11:20 UTC, MiaJLee commented on src/utils/index.ts
> +}
string이 undefined나 null일 가능성은 완전히 없는 것일까요?

2024-07-20 11:58 UTC, cla6shade commented on src/components/organisms/product/ProductOrderForm.tsx
> +              value: getValues().hasCashReceipt,
안녕하세요 멘토님, 답변이 늦었습니다. 죄송합니다!

getValues와 watch 메소드 모두 input값의 변화를 관찰하지만, Profiler로 확인해본 결과 watch를 사용하면 폼 전체가 리렌더링되고, getValues를 사용하면 uncontrolled component 처럼 상태 변화 없이 값을 관측할 수 있다는 점을 알 수 있었습니다.

따라서 validation이 수행될 때마다 getValues를 통해 값을 받아오게 된다면 리렌더링 없이도 최신 값으로 validation을 수행할 수 있다고 생각했습니다.

물론 첨부터 저렇게 생각하지는 않았고.. 일단 사용해보고 조금 더 나은 방안을 고민하다 저런 결론에 도달했습니다

2024-07-20 13:28 UTC, cla6shade commented on src/components/organisms/product/ProductOrderForm.tsx
> +              value: getValues().hasCashReceipt,
추가적인 스펙 (현금영수증 체크 해제 시 에러메시지 제거, 영수증 번호 input isabled 처리)을 구현하면서, watch를 활용한 controlled 방식의 처리의 필요성을 깨달았고 Controller 컴포넌트를 이용하여 이를 구현해봤습니다.

위 기능을 controlled 방식으로 처리하지 않으면 문제점이 발생할 수 있음을 깨달았는데요~ 이를 한번 정리해봤습니다.

기존의 방식에서는 체크박스 체크 여부를 변화시키더라도 다른 컴포넌트에서 변화를 감지할 수 없습니다. getValues()를 통해 불러온 값은 초기 렌더링 시점의 default Value에 머무르기 때문입니다. 

input의 register option으로 넘겨주는 validate 함수에서 getValues()를 사용하는 경우 타이핑 시 form의 값을 계속 호출하기 때문에 uncontrolled 하게 최신 값을 받아올 수 있지만, disabled와 같이 컴포넌트의 props로 넘겨주는 경우는 다릅니다. watch와 달리 getValues()로 받아온 내부의 값은 변하더라도 컴포넌트의 리렌더링을 예약하지는 않기 때문이라고 생각했습니다.

리팩터링한 코드는 아래와 같습니다!

```typescript

  const hasCashReceipt = watch('hasCashReceipt');
  // ...
    <Controller
          name="cashReceiptNumber"
          control={control}
          rules={{
            validate: (value: string | undefined) => {
              const pattern = /^[0-9]*$/;

              if (!value) return FormErrorMessages.RECEIPT_NUMBER_REQUIRED;

              if (!hasCashReceipt || pattern.test(value)) return true;

              return FormErrorMessages.RECEIPT_NUMBER_NOT_NUMERIC;
            },
          }}
          disabled={!hasCashReceipt}
          render={({ field }) => (
            <Input
              borderColor={defaultBorderColor}
              marginTop="5px"
              {...field}
            />
          )}
        />
  // ... 
    <Controller
          name="cashReceiptNumber"
          control={control}
          rules={{
            validate: (value: string | undefined) => {
              const pattern = /^[0-9]*$/;

              if (!value) return FormErrorMessages.RECEIPT_NUMBER_REQUIRED;

              if (!hasCashReceipt || pattern.test(value)) return true;

              return FormErrorMessages.RECEIPT_NUMBER_NOT_NUMERIC;
            },
          }}
          disabled={!hasCashReceipt}
          render={({ field }) => (
            <Input
              borderColor={defaultBorderColor}
              marginTop="5px"
              {...field}
            />
          )}
        />
```

2024-07-20 13:31 UTC, cla6shade commented on src/utils/index.ts
> +}
생각해보니 서버에서 보내는 객체 데이터에서 `없는 데이터`의 경우 빈 문자열인 `''`를 보내기보다는 아예 해당 property를 없애버리는 식으로 많이 사용했던 것 같습니다.

falsy type인지 체크하는 로직까지 추가해보겠습니다!

2024-07-20 14:39 UTC, cla6shade commented on src/hooks/useOrderFormValidation.ts
> +  });
hasCardMessageError, cardMessageErrorCaption 등을 멘토님이 말씀하신 대로 하나의 state로 관리할 시 조금 더 편리해질 것 같다는 생각이 들었습니다. 따라서 에러 여부와 dirty 여부를 관리하는 OrderFormStatus 인터페이스를 통해 각각의 input 상태를 관리하고자 했습니다.

```typescript
export interface OrderFormStatus {
  isDirty: boolean;
  errorMessage?: FormErrorMessages[string] | boolean;
}
```
```typescript
import { useEffect, useState } from 'react';
import { FormErrorMessages } from '@constants/ErrorMessage';
import { OrderRequestBody } from '@/types/request';
import { OrderFormStatus } from '@/types';
import { isEmptyString, isNumericString } from '@/utils';

interface UseOrderFormValidationProps {
  orderData: OrderRequestBody;
}

const useOrderFormValidation = ({ orderData }: UseOrderFormValidationProps) => {
  const [cardMessageStatus, setCardMessageStatus] = useState<OrderFormStatus>({
    isDirty: false,
  });
  const [receiptNumberStatus, setReceiptNumberStatus] = useState<OrderFormStatus>({
    isDirty: false,
  });

  const validateCardMessage = () => {
    const cardMessage = orderData.messageCardTextMessage;

    if (isEmptyString(cardMessage)) {
      setCardMessageStatus({
        isDirty: true,
        errorMessage: FormErrorMessages.MESSAGE_CARD_EMPTY,
      });
    }
  };

  const validateReceiptNumber = () => {
    if (!orderData.hasCashReceipt) return;

    const receiptNumber = orderData.cashReceiptNumber;

    if (isEmptyString(receiptNumber)) {
      setCardMessageStatus({
        isDirty: true,
        errorMessage: FormErrorMessages.RECEIPT_NUMBER_REQUIRED,
      });
    }

    if (!isNumericString(receiptNumber)) {
      setReceiptNumberStatus({
        isDirty: true,
        errorMessage: FormErrorMessages.RECEIPT_NUMBER_NOT_NUMERIC,
      });
    }
  };

  const validateBeforeSubmit = () => {
    validateCardMessage();
    validateReceiptNumber();
  };

  useEffect(() => {
    if (cardMessageStatus.isDirty) validateCardMessage();

    if (receiptNumberStatus.isDirty) validateReceiptNumber();
  }, [orderData.hasCashReceipt, orderData.cashReceiptNumber, orderData.messageCardTextMessage]);

  return {
    cardMessageStatus,
    setCardMessageStatus,
    receiptNumberStatus,
    setReceiptNumberStatus,
    validateBeforeSubmit,
  };
};

export default useOrderFormValidation;

```

위 hook을 통해 cardMessageStatus의 errorMessage가 falsy한 경우 에러메시지를 표시하도록 구현할 수 있겠다는 생각이 들었습니다.

확실히 하나의 state로 form의 상태를 관리하니까 훨씬 수월하고 코드를 알아보기도 쉬웠고, 서로 비슷한 타입의 input의 상태를 하나의 type으로 관리할 수 있어서 코드 재사용성도 좋은 것 같습니다!!

2024-07-20 17:20 UTC, cla6shade commented
안녕하세요 멘토님,

추가 요구사항(sessionStorage를 이용한 주문 데이터 보존)까지 구현 완료한 후 다시 푸쉬했습니다.
step2에서 구현해본 것을 조금 더 완벽하게 동작하도록 하느라 조금 오래 걸린 것 같습니다.

항상 시간내주셔서 감사드립니다!

2024-07-21 04:47 UTC, MiaJLee approved these changes
고생하셨습니다 세형님-!

2024-07-21 04:47 UTC, MiaJLee commented on src/utils/index.ts
>    return value === '';
```suggestion
  return !value
```

위와 동일한 동작일 것 같아요~

2024-07-21 04:47 UTC, merged