부산대 FE_이세형 4주차 과제 Step4
kakao-tech-campus-2nd-step2/react-product-order pull request #64
Opened 2024-07-19 07:03 UTC by cla6shade

안녕하세요 멘토님!

1시간 전에 PR 보냈던 step 3에 이어 step4의 질문까지 답해봤습니다.

감사합니다!

2024-07-19 11:22 UTC, MiaJLee requested changes
PR의 Head 브랜치가 main으로 되어있네요!
수정해주세요-!

2024-07-21 04:48 UTC, MiaJLee requested changes
@cla6shade 세형님~ 컨플릭트 한번 확인해주세요-!

2024-07-21 08:35 UTC, cla6shade commented
Conflict 해결 완료했습니다.

다음 주차가 벌써 마지막이라는게 믿기지 않네요..
마지막까지 잘 부탁드립니다!

2024-07-21 08:36 UTC, MiaJLee approved these changes
이번주도 넘 고생하셨습니다-!
끝까지 파이팅! 🔥

2024-07-21 08:36 UTC, merged