강원대 FE_이예지 4주차 과제 STEP2
kakao-tech-campus-2nd-step2/react-product-order pull request #65
Opened 2024-07-19 07:15 UTC by yeahzee0421

폼 유효성 검사 추가해서 PR 올립니다 :)!! 
항상 감사드립니다

2024-07-20 11:38 UTC, yujo11 commented
STEP1 리뷰하고 다시 오픈할게요!

2024-07-20 12:20 UTC, yujo11 requested changes
안녕하세요 예지님~

이번 주차 미션도 잘 구현해주셨네요 ㅎㅎ 

코멘트 남긴 내용 확인 부탁드립니다~ 고생 많으셨어요~~ 👍 👍 👍

2024-07-20 12:20 UTC, yujo11 commented on src/api/hooks/useGetProductDetails.ts
> +export type ProductsDetailResponseData = {
하나의 API에서 다른 응답이 올 수 있는건가요? 여기 타입이 왜 이렇게 지정되어 있는지 궁금하네요

2024-07-20 12:20 UTC, yujo11 commented on src/api/hooks/useGetProductDetails.ts
> +export const useProductDetails = (
react query option도 parameter로 받을 수 있게 만들어주면 이 hook을 보다 유연하게 사용할 수 있을거 같네요 ㅎㅎ

2024-07-20 12:20 UTC, yujo11 commented on src/api/instance/apiPath.ts
> +};
상수화는 좋으나 현재 같은 level에서 다르게 사용해야 하는 값들이 묶여있는데요.

배열로 치면 아래와 같은 상황인거 같아요 함수와 string을 별도로 관리해보셔도 좋을거 같아요

```
[ string, string, fn, fn, fn ]
```

2024-07-20 12:20 UTC, yujo11 commented on src/components/common/layouts/Split/index.tsx
> +  height: calc(-54px + 100vh);
이런 값들은 Header 등 컨텐츠가 변함에 따라 같이 변경되어야 하는데요.

상수 등을 사용해 한 군데에서만 변경하면 다른 곳들에 자동으로 style이 변경되도록 해보셔도 좋을거 같아요

2024-07-20 12:20 UTC, yujo11 commented on src/components/features/Order/Form/CashReceiptForm/index.tsx
> +  if (!/^\d*$/.test(data.receiptNumber)) {
정규식은 간편하게 사용하기 좋지만 코드가 바로 눈에 들어오지 않아 가독성이 낮아지는 단점도 있는데요.

이런 단점을 감수하고서라도 정규식을 사용해야 하는 상황인지 고민 해보셔도 좋을거 같아요 ㅎㅎ

2024-07-20 12:20 UTC, yujo11 commented on src/components/features/Order/Form/CashReceiptForm/index.tsx
> +  let receiptError = '';
`let`을 제거해보시면 좋겠네요

2024-07-20 12:20 UTC, yujo11 commented on src/components/features/Order/Form/MessageFormSection/index.tsx
> +  let messageError = '';
여기도 마찬가지로 let을 사용하지 않고 바로 return 시키는 방법을 사용해도 좋을거 같아요

2024-07-20 12:20 UTC, yujo11 commented on src/components/features/Order/OrderAsideSection/index.tsx
> +      <Divider aria-orientation="horizontal" />
어떤 컴포넌트는 `Divider`와 결합되어 있고, 어떤 컴포넌트는 결합되어 있지 않은데요.

`OrderAsideSection` 컴포넌트는 해당 컴포넌트에서 할 일에만 집중하고, 다른 컴포넌트와 조합되어 사용되는 부분에 필요한 `Divider`는 조합하는 곳에서 사용해도 좋을거 같아요

2024-07-20 12:20 UTC, yujo11 commented on src/components/features/Product/ProductAsideSection/index.tsx
> +                />
이런 path는 코드 레벨에서 봤을 때 어떤걸 보여주려고 하는지 알기가 어려운데요. 적절한 상수나 컴포넌트로 분리해보셔도 좋을거 같아요

2024-07-21 07:57 UTC, yeahzee0421 commented on src/api/hooks/useGetProductDetails.ts
> +export type ProductsDetailResponseData = {
여기서는 `API_ENDPOINT.PRODUCT_DETAILS(productId)` 엔드포인트에서 데이터를 받아오는데, 해당 api response를 보면 이미 정의해둔 GoodsData 타입뿐만 아니라 다양한 상품의 상세 정보가 추가적으로 담겨있어서(isAccessableProductPage, review 등)  `GoodsData &` 를 사용해서 새롭게 타입을 지정해주었습니다!

2024-07-21 09:28 UTC, yeahzee0421 commented on src/api/hooks/useGetProductDetails.ts
> +export const useProductDetails = (
네! 해당 내용 반영해서 커스텀 훅 작성했습니다.
```
export const useProductDetailsQuery = (
  productId: number,
  options?: UseQueryOptions<ProductDetailsData>,
): UseQueryResult<ProductDetailsData> => {
  return useQuery({
    queryKey: queryKeys.detailsByProductId(productId),
    queryFn: () => getProductDetails(productId),
    ...options,
  });
};
```

2024-07-21 09:36 UTC, yeahzee0421 commented on src/api/instance/apiPath.ts
> +};
넵 정적인 경로와 동적 함수를 분리하도록 수정했습니다.!
https://github.com/yeahzee0421/react-product-order/commit/888ffa7495eb0270de1682f660878702c3070b55

2024-07-21 09:52 UTC, yeahzee0421 commented on src/components/common/layouts/Split/index.tsx
> +  height: calc(-54px + 100vh);
넵 참고하겠습니다 :D

2024-07-21 10:11 UTC, yeahzee0421 commented on src/components/features/Order/Form/CashReceiptForm/index.tsx
> +  if (!/^\d*$/.test(data.receiptNumber)) {
네 피드백 감사합니다
정규식을 사용하는 대신 `isNaN(Number(receiptNumber)` 와 같이 메서드를 통해서 유효성 검사를 하도록 작성해보았습니다.

2024-07-21 10:15 UTC, yeahzee0421 commented on src/components/features/Order/Form/MessageFormSection/index.tsx
> +  let messageError = '';
넵 바로 return 시키도록 수정했습니다.
https://github.com/yeahzee0421/react-product-order/commit/6277bdad925af858d77ce02af25eeeede4ea67c4

2024-07-21 10:15 UTC, yeahzee0421 commented on src/components/features/Order/OrderAsideSection/index.tsx
> +      <Divider aria-orientation="horizontal" />
오오 네 피드백 감사드립니다 ㅎㅎ 
https://github.com/yeahzee0421/react-product-order/commit/56fe4a26e02d8e335661fd8127b8ffdae2f798d6

2024-07-21 10:19 UTC, yeahzee0421 commented on src/components/features/Product/ProductAsideSection/index.tsx
> +                />
네 분리했습니다. 
훨씬 가독성이 좋아졌네요! 감사드립니다

2024-07-21 12:52 UTC, yujo11 approved these changes
고생 많으셨습니다 예지님~~ 👍 👍 👍

2024-07-21 12:52 UTC, yujo11 commented on src/api/hooks/useGetProductDetails.ts
> +  options?: UseQueryOptions<ProductDetailsData>,
👍 👍 👍

2024-07-21 12:52 UTC, yujo11 commented on src/components/common/Icon/constant/index.ts
👍 👍 👍

2024-07-21 12:52 UTC, yujo11 commented on src/api/instance/apiPath.ts
> +export const dynamicPath = {
👍 👍 👍

2024-07-21 12:52 UTC, merged