강원대 FE_정다연 STEP2
kakao-tech-campus-2nd-step2/react-product-order pull request #82
Opened 2024-07-19 14:14 UTC by dandamdandam

안녕하세요 멘토님.
STEP1 리뷰반영을 아직 하지 않아 PR이 닫힌 상태가 아니지만, 과제 마감 시간이 얼마 남지 않아 급하게 STEP2 PR을 올립니다. 리뷰하기 불편해진 것 같아 너무 죄송합니다.

이 PR이 최신이니 여기서 STEP1 반영과 추가로 받은 리뷰까지 수정해서 머지를 해야할 것 같습니다! STEP1 PR은 STEP2가 완료되면 삭제하겠습니다.

[STEP1 PR](https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/29)
STEP2에 해당하는 커밋
[시작](https://github.com/kakao-tech-campus-2nd-step2/react-product-order/commit/cdb84fb8b06b6bdb0c6dfc728c8e033dbc9a3f9b) [끝](https://github.com/kakao-tech-campus-2nd-step2/react-product-order/commit/46111c441064c51c42227f3a8ef1c1dfdfbfa7a3)

STEP2에서 바뀐 부분은 크게 없습니다! 간단한 validation 작업을 3개 정도 하면서, product 페이지의 주문 옵션을 설정하는 부분을 Option Setting 컴포넌트로 나누었습니다.
하나의 컴포넌트에서 하나의 api date만 패치하는 편이 좀 더 깔끔하겠다는 생각에서 그렇게 구현했습니다. 추후 상품 옵션을 설정할 수 있는 기능을 해당 컴포넌트에서 구현할 예정이여서, 코드가 길어질 것 같기도 하고요.

2024-07-19 14:18 UTC, dandamdandam commented
https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/29#pullrequestreview-2187829313

2024-07-20 04:37 UTC, lazy-sky requested changes
저번 리뷰 내용 이후로 크게 바뀐 부분은 없는 거 같습니다. 컨플릭트 해결 후에 머지하도록 하겠습니다! (페칭 데이터를 어떤 식으로 다룰 것인가에 대해서만 좀 더 고민해보면 좋을 거 같습니다)

2024-07-20 04:37 UTC, lazy-sky commented on src/entities/Product.ts
> +interface ProductDetail extends ProductData {
일반적으로 data라는 이름은 피하는 게 좋습니다. 너무 추상적이기 때문이죠. 그냥 Product라고 표현하면 의미를 못담는 느낌일까요?

2024-07-20 04:37 UTC, lazy-sky commented on src/entities/Product.ts
> +interface ProductDetail extends ProductData {
혹시 interface, type임을 확실히 하고 싶으신 거라면 `IProduct`(interface인 경우), `TPrdouct`(type인 경우)라고 명명하는 방식도 있습니다.

2024-07-22 01:52 UTC, dandamdandam commented on src/entities/Product.ts
> +interface ProductDetail extends ProductData {
api 명세서에 ProductData라고 명시되어 있어 그 이름을 그대로 사용했습니다. 특정 객체에는 한가지 명칭을 일관적으로 사용하는게 좋다겠다고 생각했습니다!

https://github.com/dandamdandam/react-product-order/blob/46111c441064c51c42227f3a8ef1c1dfdfbfa7a3/oas.yaml#L315

2024-07-22 03:31 UTC, dandamdandam commented
step1 피드백 사항 확인했습니다!

https://github.com/kakao-tech-campus-2nd-step2/react-product-order/pull/82#issuecomment-2239288828

2024-07-22 05:12 UTC, merged