강원대 FE _ 구희원 4주차 과제 step1 ~ step2 제출합니다.
kakao-tech-campus-2nd-step2/react-product-order pull request #86
Opened 2024-07-19 14:36 UTC by HeHelee

이번주에는 개념 정리하고 하느라고 step2까지만 구현했습니다. 후에는 step3 까지 해결하겠습니다. 코치님한테 궁금한점이 있습니다. 저는 과제를 할 때 gpt가 써준 코드를 저는 이해하면서 과제를 수행합니다. (제가 스스로 다 하려 하면 시간이 많이 부족해져서요..) 그러다 보니 코딩 실력이 느는건지 잘 감이 잡히지 않습니다. 또 타입스크립트를 저는 처음 이번에 과제하면서 접하는거라 조금 서툴어서 낯설기도 합니다. 어느정도 gpt를 이용해서 해야 하는걸까요 ? 그리고 강사님이 처음 코딩배우셨을 때 어떻게 접하면서 공부하셨는지도 궁금합니다. (잘하고 싶은데 마음처럼 잘 안되네요 .. ㅠㅠ)

2024-07-20 12:29 UTC, yujo11 requested changes
안녕하세요 희원님~

GPT같은 툴을 잘 이용해서 학습하는 것은 굉장히 좋다고 생각합니다.

다만 그 과정에서 추천해주는대로 그냥 사용하는 것이 아니라 "같이"만들어나간다고 생각하고 적으신 코드의 어디를 집어오더라도 "왜" 이렇게 코드를 작성했는지 이해하시면서 진행을 하시면 좋을거 같아요 ㅎㅎ

프로그래밍 실력이라는게 정량적으로 측정하기 어렵기 때문에 실력이 늘고 있는지 알기는 어려운 부분이 있을텐데요. 이전에 희원님이 제출하신 미션들 PR을 보면서 셀프리뷰를 한번 해보셔도 좋을거 같아요. 그 과정에서 이전에 작성한 코드에 아쉬운 부분들이 눈에 들어온다면 그만큼 희원님이 성장하셨다고 느끼실 수 있을겁니다 ㅎㅎ

이번 주도 고생 많으셨습니다 ~~  👍 👍 👍

2024-07-20 12:29 UTC, yujo11 commented on src/api/hooks/products.ts
> +    staleTime: 60000,
numeric seprator를 사용해보시면 좋겠네요 ~
```suggestion
    staleTime: 60_000,
```

2024-07-20 12:29 UTC, yujo11 commented on src/api/hooks/products.ts
> +    staleTime: 60000,
그리고 staleTime에 60,000이 들어간 배경이 궁금하네요 ㅎㅎ

2024-07-20 12:29 UTC, yujo11 commented on src/api/hooks/products.ts
> +export const useGetProductOptions = (productId: string) => {
option도 받을 수 있게 만들어주면 더 유연하게 사용이 가능할거 같아요 ㅎㅎ

2024-07-20 12:29 UTC, yujo11 commented on src/api/hooks/products.ts
> +const getProductOptionsPath = (productId: string) => `/v1/products/${productId}/options`;
이게 별도의 함수로 분리되어 있을 필요가 있을까요?

2024-07-20 12:29 UTC, yujo11 commented on src/api/hooks/products.ts
> +  const response = await fetchInstance.get<ProductOptionsData>(getProductOptionsPath(productId));
아래처럼만 작성되어도 충분할거 같은데 분리하신 배경이 궁금하네요

```suggestion
  const response = await fetchInstance.get<ProductOptionsData>(`/v1/products/${productId}/options`);
```

2024-07-20 12:29 UTC, yujo11 commented on src/api/hooks/useGetProductDetail.ts
> +  console.log(`Fetching product details for productId: ${productId}`);
의도적으로 남겨둔 console.log 일까요?

2024-07-20 12:29 UTC, yujo11 commented on src/pages/Order/index.tsx
> +    if (/^\d*$/.test(value)) {
정규식을 사용하게 되면 코드가 한 눈에 들어오지 않아 가독성이 떨어진다는 단점이 있는데요.

이런 단점을 감수하고서라도 사용해야 하는 상황일지도 같이 고민해보시면 좋겠네요

2024-07-20 12:29 UTC, yujo11 commented on src/pages/ProductDetail/index.tsx
> +      if (data) {
depth를 2개 가질 필요가 없어 보이네요
```suggestion
    } else if (data) {
```

2024-07-20 12:29 UTC, yujo11 commented on src/pages/ProductDetail/index.tsx
> +      alert('로그인이 필요한 메뉴입니다.\n로그인 페이지로 이동하시겠습니까?');
`alert`의 문구가 조금 어색하게 느껴지네요 ㅎㅎ

2024-07-20 12:29 UTC, yujo11 commented on src/pages/ProductDetail/index.tsx
> +  const { productId } = useParams<{ productId: string }>();
productid가 존재하지 않으면 어떻게 되나요?

2024-07-22 06:24 UTC, HeHelee commented on src/api/hooks/products.ts
> +    staleTime: 60000,
staleTime을 설정한 이유는 데이터가 유지되는 시간을 설정하여, 해당 시간 동안 캐시된 데이터를 사용해서 불필요한 서버 요청을 줄이고, 사용자에게 빠른 응답을 제공할 수 있기 때문입니다.

2024-07-22 06:25 UTC, HeHelee commented on src/api/hooks/products.ts
> +export const useGetProductOptions = (productId: string) => {
넵 피드백 반영하겠습니다 ㅎㅎ

2024-07-22 06:56 UTC, HeHelee commented on src/api/hooks/useGetProductDetail.ts
> +  console.log(`Fetching product details for productId: ${productId}`);
앗 이건 실수입니다 ㅎㅎ 고치겠습니다.

2024-07-22 07:37 UTC, HeHelee commented on src/api/hooks/products.ts
> +  const response = await fetchInstance.get<ProductOptionsData>(getProductOptionsPath(productId));
코드를 훑어보니 product api를 여러 곳에서 호출하는 부분이 없네요. 제가 해당 부분을 불러온 이후는 이후에 api를 다른 곳에서 불러올 수 있지 않을까 하는 부분에서 나눴습니다 !

2024-07-23 06:05 UTC, HeHelee commented on src/pages/Order/index.tsx
> +    if (/^\d*$/.test(value)) {
넵 한번 다른 방법 모색해보겠습니다

2024-07-23 06:20 UTC, HeHelee commented on src/pages/ProductDetail/index.tsx
> +      if (data) {
넵 수정하겠습니다.

2024-07-23 06:21 UTC, HeHelee commented on src/pages/ProductDetail/index.tsx
> +      alert('로그인이 필요한 메뉴입니다.\n로그인 페이지로 이동하시겠습니까?');
적절한 문구로 바꾸겠습니다 ㅎㅎ

2024-07-23 06:40 UTC, HeHelee commented on src/pages/ProductDetail/index.tsx
> +  const { productId } = useParams<{ productId: string }>();
productId가 없으면 useParams 훅을 사용해서 proudId를 가져올 때 undefined가 됩니다.

2024-07-23 06:41 UTC, HeHelee commented on src/pages/ProductDetail/index.tsx
> +      alert('로그인이 필요한 메뉴입니다.\n로그인 페이지로 이동하시겠습니까?');
넵 반영해서 수정하겠습니다 !

2024-07-23 06:41 UTC, HeHelee commented on src/pages/ProductDetail/index.tsx
> +      if (data) {
넵 !

2024-07-23 06:42 UTC, HeHelee commented on src/pages/ProductDetail/index.tsx
> +  const { productId } = useParams<{ productId: string }>();
useParams 훅을 이용해서 productId가 존재하지 않는다면 undefined가 불러와집니다.

2024-07-23 15:00 UTC, yujo11 approved these changes
고생하셨어요 희원님~~

2024-07-23 15:00 UTC, merged