부산대 FE_최윤성_4주차 과제 step2
kakao-tech-campus-2nd-step2/react-product-order pull request #96
Opened 2024-07-20 02:18 UTC by yunseong0404

멘토님 안녕하세요 4주차 과제 step2 제출합니다!

2024-07-21 10:37 UTC, MiaJLee commented
@yunseong0404 
윤성님~ 여기도 컨플릭트 해결해주세요!

2024-07-21 22:28 UTC, MiaJLee requested changes
윤성님~ 컨플릭트 해결해주세요!

2024-07-22 06:34 UTC, yunseong0404 commented
컨플릭트 해결 했습니다!

2024-07-22 08:18 UTC, MiaJLee approved these changes
고생하셨습니다~

2024-07-22 08:18 UTC, MiaJLee commented on src/api/hooks/useGetProductsDetail.ts
> +        setLoading(false);
이 코드는 finally와 중복되니 제거해도 될 것 같아요~

2024-07-22 08:18 UTC, MiaJLee commented on src/api/hooks/useGetProductsDetail.ts
> +        setLoading(false);
과제가 딜레이되어서 일단 머지 할게요

2024-07-22 08:18 UTC, merged